### ISSUE TITLE
(document) Doc for data review

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Zerda#208]
Prerequisite: metrics defined  (See also #49 )
Acceptance Criteria:
Working document able to kick off data review.
a. in-tree documentation, 
b. following the data policies and collecting opt-out for only Type 1, Type 2 data, 
c. having a specific person assigned to be in charge of looking at and analyzing the data or removing probes when they are not needed any more). See the document on data collection: https://wiki.mozilla.org/Firefox/Data_Collection

**Comment by chianger** [comment]
@liuche

**Comment by liuche** [comment]
Hi @chianger, I've made some comments in the spreadsheet:
https://docs.google.com/spreadsheets/d/1ey5vAjAvwKgzWud0-Rr9GpKWJfETpkuuljNYyMz-rVg/edit#gid=0

A few questions:

- Is telemetry opt-out for Zerda? This should also be documented in the in-tree documentation.
- Please check with Elvin about a privacy policy. In terms of data review, since this will be a different product from Firefox, you might include a different privacy policy.
- Can you remind me what this is based off of? Is it UI Telemetry from Focus Android (not Fennec Android), from this repository?
https://github.com/mozilla-mobile/telemetry-android

Finally, in terms of in-tree documentation, ideally Zerda could have something in the wiki section, similar to https://github.com/mozilla-mobile/focus-android/wiki/Telemetry

Thank you for your patience! Please ping me on slack or irc once you have the documentation up. The probes you are proposing to collect look good to me, except for some clarifications on the comments I've made in the spreadsheet.

**Comment by chianger** [comment]
Yes. It is opt-out for Zerda.
We do talk to Elvin and he's helping us on that privacy notice.
I created a bug "Bug 1397692 - Project Zerda data review", and hopefully that helps you to keep track.

**Comment by liuche** [comment]
Hi @chianger, I don't think I got a response on my last question from my comment:

* Can you remind me what this is based off of? Is it UI Telemetry from Focus Android (not Fennec Android), from this repository?
https://github.com/mozilla-mobile/telemetry-android

**Comment by chianger** [comment]
@liuche 
Zelda is using the library from Focus for Android, to send telemetry including both core ping and event ping.

As to Adjust SDK, we also leverage the one from Focus for Android.
Just  that we built with our newly generated token on release build.

**Comment by idiotmax** [comment]
Github Wiki page: https://github.com/mozilla-tw/Zerda/wiki/Telemetry
