### ISSUE TITLE
[Smoke Test] URL flickers while tapping new Top Sites

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#220]
DuT: Advan i5C
Build 303

STR:
1. Launch Zerda
2. Tap any Top Sites
3. Tap Home
4. Tap another Top Sites and observe URL field

Expected Result:

4. The latest website we visit is displayed on URL field

Actual Result:

4. Previous URL flickers on the URL field

**Comment by Conjuror** [comment]
Some times, the URL will display incorrectly.

**Comment by Conjuror** [comment]
https://drive.google.com/a/mozilla.com/file/d/0B11T5xYLeXAOeDl3ZzVCTDR3bVE/view?usp=sharing

**Comment by dakaizou** [comment]
Still happening in build 623
DuT: advan

**Comment by mTwTm** [comment]
09-18 19:07:04.777 25406-25406/org.mozilla.rocket.debug.tyu E/mTwTm: updateURL to : https://m.youtube.com/ by :
                                                                     android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                     android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
                                                                     org.mozilla.focus.fragment.WebFragment.onCreateView(WebFragment.java:53)
09-18 19:07:04.821 25406-25406/org.mozilla.rocket.debug.tyu E/mTwTm: updateURL to : https://www.instagram.com/ by :
                                                                     org.mozilla.focus.webkit.WebkitView$FocusWebChromeClient.onProgressChanged(WebkitView.java:200)
                                                                     org.mozilla.focus.webkit.WebkitView$CallbackWrapper.onURLChanged(WebkitView.java:325)
                                                                     org.mozilla.focus.fragment.BrowserFragment$2.onURLChanged(BrowserFragment.java:362)
09-18 19:07:05.048 25406-25406/org.mozilla.rocket.debug.tyu E/mTwTm: updateURL to : https://m.youtube.com/ by :
                                                                     org.mozilla.focus.webkit.WebkitView$FocusWebChromeClient.onProgressChanged(WebkitView.java:200)
                                                                     org.mozilla.focus.webkit.WebkitView$CallbackWrapper.onURLChanged(WebkitView.java:325)
                                                                     org.mozilla.focus.fragment.BrowserFragment$2.onURLChanged(BrowserFragment.java:362)
09-18 19:07:05.048 25406-25406/org.mozilla.rocket.debug.tyu E/mTwTm: onPageFinished : https://m.youtube.com/
09-18 19:07:05.049 25406-25406/org.mozilla.rocket.debug.tyu E/mTwTm: updateURL to : https://m.youtube.com/ by :
                                                                     org.mozilla.focus.webkit.FocusWebViewClient.onPageFinished(FocusWebViewClient.java:118)
                                                                     org.mozilla.focus.webkit.WebkitView$CallbackWrapper.onURLChanged(WebkitView.java:325)
                                                                     org.mozilla.focus.fragment.BrowserFragment$2.onURLChanged(BrowserFragment.java:362)
09-18 19:07:05.049 25406-25406/org.mozilla.rocket.debug.tyu E/mTwTm: updateURL to : https://m.youtube.com/ by :
                                                                     org.mozilla.focus.webkit.WebkitView$FocusWebChromeClient.onProgressChanged(WebkitView.java:200)
                                                                     org.mozilla.focus.webkit.WebkitView$CallbackWrapper.onURLChanged(WebkitView.java:325)
                                                                     org.mozilla.focus.fragment.BrowserFragment$2.onURLChanged(BrowserFragment.java:362)
09-18 19:07:05.050 25406-25406/org.mozilla.rocket.debug.tyu E/mTwTm: updateURL to : https://m.youtube.com/ by :
                                                                     org.mozilla.focus.webkit.WebkitView$FocusWebChromeClient.onProgressChanged(WebkitView.java:200)
                                                                     org.mozilla.focus.webkit.WebkitView$CallbackWrapper.onURLChanged(WebkitView.java:325)
                                                                     org.mozilla.focus.fragment.BrowserFragment$2.onURLChanged(BrowserFragment.java:362)
09-18 19:07:05.054 25406-25406/org.mozilla.rocket.debug.tyu E/mTwTm: updateURL to : https://m.youtube.com/ by :
                                                                     org.mozilla.focus.webkit.WebkitView$FocusWebChromeClient.onProgressChanged(WebkitView.java:200)
                                                                     org.mozilla.focus.webkit.WebkitView$CallbackWrapper.onURLChanged(WebkitView.java:325)
                                                                     org.mozilla.focus.fragment.BrowserFragment$2.onURLChanged(BrowserFragment.java:362)
09-18 19:07:05.055 25406-25406/org.mozilla.rocket.debug.tyu E/mTwTm: onPageFinished : https://m.youtube.com/
09-18 19:07:05.055 25406-25406/org.mozilla.rocket.debug.tyu E/mTwTm: updateURL to : https://m.youtube.com/ by :
                                                                     org.mozilla.focus.webkit.FocusWebViewClient.onPageFinished(FocusWebViewClient.java:118)
                                                                     org.mozilla.focus.webkit.WebkitView$CallbackWrapper.onURLChanged(WebkitView.java:325)
                                                                     org.mozilla.focus.fragment.BrowserFragment$2.onURLChanged(BrowserFragment.java:362)
09-18 19:07:05.056 25406-25406/org.mozilla.rocket.debug.tyu E/mTwTm: updateURL to : https://m.youtube.com/ by :
                                                                     org.mozilla.focus.webkit.WebkitView$FocusWebChromeClient.onProgressChanged(WebkitView.java:200)
                                                                     org.mozilla.focus.webkit.WebkitView$CallbackWrapper.onURLChanged(WebkitView.java:325)
                                                                     org.mozilla.focus.fragment.BrowserFragment$2.onURLChanged(BrowserFragment.java:362)
09-18 19:07:05.057 25406-25406/org.mozilla.rocket.debug.tyu E/mTwTm: updateURL to : https://m.youtube.com/ by :
                                                                     org.mozilla.focus.webkit.WebkitView$FocusWebChromeClient.onProgressChanged(WebkitView.java:200)
                                                                     org.mozilla.focus.webkit.WebkitView$CallbackWrapper.onURLChanged(WebkitView.java:325)
                                                                     org.mozilla.focus.fragment.BrowserFragment$2.onURLChanged(BrowserFragment.java:362)
09-18 19:07:05.061 25406-25406/org.mozilla.rocket.debug.tyu E/mTwTm: onPageStarted : https://www.instagram.com/
09-18 19:07:05.062 25406-25406/org.mozilla.rocket.debug.tyu E/mTwTm: updateURL to : https://www.instagram.com/ by :
                                                                     org.mozilla.focus.webkit.FocusWebViewClient$1.run(FocusWebViewClient.java:71)
                                                                     org.mozilla.focus.webkit.WebkitView$CallbackWrapper.onURLChanged(WebkitView.java:325)
                                                                     org.mozilla.focus.fragment.BrowserFragment$2.onURLChanged(BrowserFragment.java:362)
09-18 19:07:05.696 25406-25406/org.mozilla.rocket.debug.tyu E/mTwTm: updateURL to : https://m.youtube.com/ by :
                                                                     org.mozilla.focus.webkit.WebkitView$FocusWebChromeClient.onProgressChanged(WebkitView.java:200)
                                                                     org.mozilla.focus.webkit.WebkitView$CallbackWrapper.onURLChanged(WebkitView.java:325)
                                                                     org.mozilla.focus.fragment.BrowserFragment$2.onURLChanged(BrowserFragment.java:362)
09-18 19:07:05.817 25406-25406/org.mozilla.rocket.debug.tyu E/mTwTm: onPageFinished : https://www.instagram.com/
09-18 19:07:05.819 25406-25406/org.mozilla.rocket.debug.tyu E/mTwTm: onPageFinishedInner
09-18 19:07:05.821 25406-25406/org.mozilla.rocket.debug.tyu E/mTwTm: updateURL to : https://www.instagram.com/ by :
                                                                     org.mozilla.focus.webkit.FocusWebViewClient.onPageFinished(FocusWebViewClient.java:118)
                                                                     org.mozilla.focus.webkit.WebkitView$CallbackWrapper.onURLChanged(WebkitView.java:325)
                                                                     org.mozilla.focus.fragment.BrowserFragment$2.onURLChanged(BrowserFragment.java:362)
09-18 19:07:05.822 25406-25406/org.mozilla.rocket.debug.tyu E/mTwTm: updateURL to : https://www.instagram.com/ by :
                                                                     org.mozilla.focus.webkit.WebkitView$FocusWebChromeClient.onProgressChanged(WebkitView.java:200)
                                                                     org.mozilla.focus.webkit.WebkitView$CallbackWrapper.onURLChanged(WebkitView.java:325)
                                                                     org.mozilla.focus.fragment.BrowserFragment$2.onURLChanged(BrowserFragment.java:362)
09-18 19:07:05.969 25406-25406/org.mozilla.rocket.debug.tyu E/mTwTm: updateURL to : https://www.instagram.com/ by :
                                                                     org.mozilla.focus.webkit.WebkitView$FocusWebChromeClient.onProgressChanged(WebkitView.java:200)
                                                                     org.mozilla.focus.webkit.WebkitView$CallbackWrapper.onURLChanged(WebkitView.java:325)
                                                                     org.mozilla.focus.fragment.BrowserFragment$2.onURLChanged(BrowserFragment.java:362)
09-18 19:07:06.154 25406-25406/org.mozilla.rocket.debug.tyu E/mTwTm: updateURL to : https://www.instagram.com/ by :
                                                                     org.mozilla.focus.webkit.WebkitView$FocusWebChromeClient.onProgressChanged(WebkitView.java:200)
                                                                     org.mozilla.focus.webkit.WebkitView$CallbackWrapper.onURLChanged(WebkitView.java:325)
                                                                     org.mozilla.focus.fragment.BrowserFragment$2.onURLChanged(BrowserFragment.java:362)
09-18 19:07:07.577 25406-25406/org.mozilla.rocket.debug.tyu E/mTwTm: updateURL to : https://www.instagram.com/ by :
                                                                     org.mozilla.focus.webkit.WebkitView$FocusWebChromeClient.onProgressChanged(WebkitView.java:200)
                                                                     org.mozilla.focus.webkit.WebkitView$CallbackWrapper.onURLChanged(WebkitView.java:325)
                                                                     org.mozilla.focus.fragment.BrowserFragment$2.onURLChanged(BrowserFragment.java:362)
09-18 19:07:07.591 25406-25406/org.mozilla.rocket.debug.tyu E/mTwTm: updateURL to : https://www.instagram.com/ by :
                                                                     org.mozilla.focus.webkit.WebkitView$FocusWebChromeClient.onProgressChanged(WebkitView.java:200)
                                                                     org.mozilla.focus.webkit.WebkitView$CallbackWrapper.onURLChanged(WebkitView.java:325)
                                                                     org.mozilla.focus.fragment.BrowserFragment$2.onURLChanged(BrowserFragment.java:362)
09-18 19:07:07.593 25406-25406/org.mozilla.rocket.debug.tyu E/mTwTm: updateURL to : https://www.instagram.com/ by :
                                                                     org.mozilla.focus.webkit.WebkitView$FocusWebChromeClient.onProgressChanged(WebkitView.java:200)
                                                                     org.mozilla.focus.webkit.WebkitView$CallbackWrapper.onURLChanged(WebkitView.java:325)
                                                                     org.mozilla.focus.fragment.BrowserFragment$2.onURLChanged(BrowserFragment.java:362)
09-18 19:07:07.594 25406-25406/org.mozilla.rocket.debug.tyu E/mTwTm: onPageFinished : https://www.instagram.com/
09-18 19:07:07.596 25406-25406/org.mozilla.rocket.debug.tyu E/mTwTm: onPageFinishedInner
09-18 19:07:07.598 25406-25406/org.mozilla.rocket.debug.tyu E/mTwTm: updateURL to : https://www.instagram.com/ by :
                                                                     org.mozilla.focus.webkit.FocusWebViewClient.onPageFinished(FocusWebViewClient.java:118)
                                                                     org.mozilla.focus.webkit.WebkitView$CallbackWrapper.onURLChanged(WebkitView.java:325)
                                                                     org.mozilla.focus.fragment.BrowserFragment$2.onURLChanged(BrowserFragment.java:362)


From the log we can see:
1. Some url updates are due to onPageFinished from savedInstanceState. we should avoid updating with those.
2. Some url updates are initiated by onProgressChanged and is incorrect even after onPageStarted, this shows that probably we're making the wrong assumption to intercept url changes in onProgress. Let's remove this.

**Comment by cssjh** [comment]
**Verified** on 1105.
