### ISSUE TITLE
[Smoke test] Buttons from the buttom is overlapped with menu bar

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#322]
For an example, the settings buttons of twitter are covered by menu bar

**Comment by Conjuror** [comment]
![issue](https://user-images.githubusercontent.com/1625148/29440901-ea2b63e2-83fa-11e7-8d0e-595540efce76.png)

**Comment by mTwTm** [comment]
The Webview is currently pushed by the url bar. The menu button will be covered instead if we're not pushing the webview down. A (pretty painful) webview size change handling would be required to solve is thoroughly. If we decided to deal with this I would suggest triaging this as a P0 since it requires architectural change.

**Comment by mTwTm** [comment]
Side note: In #166 we've solved a problem which was a layout problem. before we fixed #166, the webview is too large even if we didn't have urlbar shown.

**Comment by chianger** [comment]
Decision: make URL bar fixed

**Comment by Conjuror** [comment]
good on build 540. tested w/ Redmi for twitter.com and maps.google.com
