### ISSUE TITLE
[Smoke Test] Screenshot editor can open deleted image

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#478]
After deleting image from other app (e.g. Gallery), screenshot editor can still open deleted image with blank screen

Build: 623
DuT: Samsung J7 Prime

**Comment by mTwTm** [comment]
It is also possible that we show items that are on sdcard and the sdcard is removed.
Proposing we need some error handling here like we have for downloads:
1. Do not enter file viewer if the files is deleted.
2. If the files is deleted, give user a hint (not sure if should be P2)
I'm proposing for a hint rather than a automatic deleted because for the case for sdcard, user might insert it later.

**Comment by mTwTm** [comment]
Confirm UX suggesting to add a placeholder

**Comment by dakaizou** [comment]
verified in build 790
