### ISSUE TITLE
[dogfooding] Unify settings color theme

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#729]
System theme color : text selected color/ dialogue /Settings/ choices

Build 950

**Comment by chianger** [comment]
need visual to take a look before we can determine the priority.

**Comment by fangshih** [comment]
Here are the places that need to make some adjustments 

**Text selection** 
The select box color needs to change to light blue  (#ADE1F5) instead of purple. Also for the select handle bar, it should be #0A84FF
![text selection](https://user-images.githubusercontent.com/4862573/30476972-44890ff2-9a3e-11e7-8a1f-249e0ba816f1.png)

**Dialogue**
All the action buttons here, need to use #0A84FF 
![dialogue action buttons](https://user-images.githubusercontent.com/4862573/30477115-aab8c268-9a3e-11e7-9197-1f8f2b174fae.png)

**Settings page / About page** 
Blue highlight and switch button also need to use #0A84FF.
Learn more < remove underline
![settings](https://user-images.githubusercontent.com/4862573/30477244-09779900-9a3f-11e7-965a-2351357ac5dc.png)

**Screenshot** 
Image info > made some adjustments on the font weight and layout. 
![dialogues](https://user-images.githubusercontent.com/4862573/30477165-d01db68a-9a3e-11e7-84cb-683336613af6.png)

**Download panel** 
The secondary text is not following the visual spec. Text color should be #737373
![download panel](https://user-images.githubusercontent.com/4862573/30477291-36ca6572-9a3f-11e7-8282-3006659c73aa.png)

Let me know if you have any questions, thanks!

**Comment by Conjuror** [comment]
Remove UX&VD by inputs from Fang.

**Comment by Conjuror** [comment]
Moved to P1 as we are targeting to ship with it.

**Comment by carol-mozilla** [comment]
Both "search suggestion" and "Text selection" highlight should be the same color : 
fill: #0a84ff 100%
opacity: 30%
Thanks! @Conjuror

**Comment by Conjuror** [comment]
Thanks !!

**Comment by dakaizou** [comment]
verified in build 1412 RC 1
