### ISSUE TITLE
Downloads not shown in Downloads panel if there's no internet connection

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#752]
STR:
1. Long tap on a image
2. Turn off internet connection
3. Tap on Save image
4. Turn on internet connection

The file was still downloaded after turning on internet connection, but it didn't appear in Downloads.
Build: 955
DuT: Samsung

**Comment by Conjuror** [comment]
It's acceptable if there's no download info in the Download Panel due to no response from Android Download Manager at the first moment. Still, the intent is sent and download manager will back to work once there's network connection. We should be able to let user know that his/her file has been downloaded. Suggest to P1.

**Comment by WeiWW** [comment]
It will appear in Download panel on my Samsung J2. So does this  appear on certain device or all the device?

**Comment by dakaizou** [comment]
@WeiWW  It happens on Samsung J7, Advan, Andromax
Oppo works fine.

Build: 1072

**Comment by WeiWW** [comment]
I test on Advan work fine. It's probably we modified the download progress, so fix this.

**Comment by dakaizou** [comment]
Looks good on Redmi, mito, Z3C too. 
Close as invalid
