### ISSUE TITLE
Turbo Mode toggle event is not passed to webview

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Zerda#787]
Compare with Focus
On Zerda, TP on/off does not show any difference when you visit cnn.com / cnet.com

**Comment by Conjuror** [comment]
It seems the trigger is broken.

STR

> Turn off Turbo Mode from Onboarding → Visit CNN → Turbo mode off
> Turn on Turbe Mode from Onboarding → Visit CNN → Turnbo mode on
> Turbo mode button will refresh the page but didn't change turbo mode behavior

**Comment by Conjuror** [comment]
Back to Build 790 (#662) and the issue is the same.

One more finding is that it seems to work with webview life cycle.
If you restart the app, set the app with turbo on/off and visit a web page. You'll see the page is loaded with turbo mode on/off as expected and the turbo mode toggle doesn't work functionally. However, if you change your app language (which will restart the webview from home), you have another chance to set your turbo mode to on/off again.

**Comment by mTwTm** [comment]
Turbo Mode toggle event changes the preference, and this preference is loaded every time the webview is created, thus give us a feeling that the toggle is only working after the webview is recreated. We should pass the setting change to webview as soon as it happens too.

**Comment by cssjh** [comment]
**Verified** on 1072.
