### ISSUE TITLE
Search suggestion will direct to yahoo directly

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#890]
STR:

1. Launch Zerda
2. Tap Search
3. Type "yahoo"
4. Tap on search suggestion: "yahoo"

Expected Result:

4. Search "yahoo" by set search engine

Actual Result:

4. Go to "yahoo.com" directly

Build 1158

**Comment by dakaizou** [comment]
It may have something to do with autocompletion.
Type in "k" and long tap each suggestion. Tap on the ones with autocompleted text will redirect users website accordingly, and those without autocompleted text will search the suggestion.

**Comment by mTwTm** [comment]
It's actually a bug. If what you selected is equal to what you have inputted we will replace former with the latter which does not make any change.

AND WE'RE USING THE WHOLE STRING TO SEARCH rather than only the user input part (for this in stance, it is we're using yahoo.com rather then yahoo)

Should replace

    public void onCommit(boolean isSuggestion) {
        final String input = urlView.getText().toString();

to

        final String input = urlView.getOriginalText().toString();

**Comment by Conjuror** [comment]
Suggest to P1 as major function failure

**Comment by dakaizou** [comment]
verified in build 1372
